#!/bin/bash

# install common utility packages
apt-get update && apt-get install -y curl htop lvm2 ntp

# Setup docker engine
apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
apt-get update && apt-get install -y \
        apt-transport-https \
            linux-image-extra-$(uname -r)
echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" | tee /etc/apt/sources.list.d/docker.list

# install docker engine
apt-get update && apt-get install -y docker-engine

