#!/bin/bash

service docker stop

# NOTE: prefer the first available spare disk
dev=`lsblk | grep disk | sed -n '2p' | awk '{print $1}'`
storage_opts=

if [ -x /sbin/pvcreate ] && [ ! -z ${dev} ]; then
    [ -d /var/lib/docker ] && rm -rf /var/lib/docker
    pvcreate /dev/${dev}
    vgcreate vg-docker /dev/${dev}
    lvcreate -l 90%FREE -n data vg-docker
    lvcreate -l 10%FREE -n metadata vg-docker
    # Setup DOCKER_OPTS
    storage_opts="y"
fi
echo DOCKER_OPTS="--config-file=/etc/docker/daemon.json" >/etc/default/docker

if [ -z $storage_opts ]; then
cat <<\EOF >/etc/docker/daemon.json
{
    "hosts": [
        "unix:///var/run/docker.sock"
    ]
}
EOF
else
cat <<\EOF >/etc/docker/daemon.json
{
    "hosts": [
        "unix:///var/run/docker.sock"
    ],
    "storage-driver": "devicemapper",
    "storage-opts": [
        "dm.datadev=/dev/vg-docker/data",
        "dm.metadatadev=/dev/vg-docker/metadata"
    ]
}
EOF
fi

service docker start

# FIXME: better way to confirm docker daemon started
while ! docker info &>/dev/null; do sleep 3; done

docker network create --driver bridge isolated_nw

docker create --restart=always --name logrotate \
    -v /var/lib/docker/containers:/var/lib/docker/containers:rw \
    tutum/logrotate

# clear key.json with the intent that AMI from this build will have uniqe
# Docker ID for Swarm
rm -f /etc/docker/key.json

